### ISSUE TITLE
在IOS中webView显示空白

### ISSUE THREAD

**Issue by MrRetro** [z372183629/react-native-webview-amap-demo#1]
如题,直接在IOS跑你的demo,出现空白。我检测了renderError发现，页面是有被执行的！！！

**Comment by leejialing** [comment]
改好了，实际是这个问题： https://segmentfault.com/a/1190000002933776
用模拟器运行，会先弹出postMessage的红屏错误，这个可以忽略。

**Comment by ivybaby** [comment]
我运行的时候在模拟器上没有出来地图，搜索什么出来的
