### ISSUE TITLE
在模拟器上可以用么

### ISSUE THREAD

**Issue by phonet** [z372183629/react-native-webview-amap-demo#4]
老哥,你这例子在模拟器上可以运行吗?我在Android模拟器上运行地图出不来,并且webview加载本地html文件似乎只能放在android目录下assets目录下才能加载是吧?我的RN版本是0.47.2

**Comment by leejialing** [comment]
debug模式使用require是可以的，release编译因为RN不会吧html文件打包进去，所以只能放在assets下

**Comment by leejialing** [comment]
模拟器的webview内核也许不兼容
我刚试过模拟器确实不行，我的环境是macOS High Sierra，React Packager 显示模拟器使用的AppleWebKit/537.36
真机完全可以跑起来

**Comment by phonet** [comment]
@z372183629 多谢指导,之前是我弄错了,debug下require是可以的,但是android打包就只能把html放入assets里面了,已经按照这种思路在RN里面集成高德地图,非常好

**Comment by samlinWORLD** [comment]
@phonet 你好，RN集成高德地图请求怎么实现的，有demo参考吗，谢谢大佬

**Comment by phonet** [comment]
@samlinWORLD 我是直接在RN的webview里面加载html，在html里面使用web的方式使用高德地图
